version: '3'

services:

  sqlsampleapp:
    build: .
    environment:
      - spring.datasource.url=jdbc:mysql://todolistdb:3306/todolist?createDatabaseIfNotExist=true
    ports:
      - "8080:8080"
    depends_on:
      - todolistdb
    networks:
      - sqlsampleappnet

  todolistdb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - sqlsampleappnet

networks:
  sqlsampleappnet:
